### ISSUE TITLE
What is `require("lsp_python")`?

### ISSUE THREAD

**Issue by nyngwang** [renstrom/dotfiles#1]
As title. I try to follow your setup related to pyright + diagnosticls. Is lsp_python a plugin I need to install or it's something default from neovim?

https://github.com/lithammer/dotfiles/blob/7c561e0a568ec717018639e128e8eea936a442a8/.config/nvim/lua/lsp.lua#L199

And I also want to know about the following `diagnosticls.filetypes`, `diagnosticls.formatters`, `diagnosticls.linters`. Are these settings built-in from the `diagnosticls`? Or these are you own setup?

```
local diagnosticls = require("diagnosticls")
```

https://github.com/lithammer/dotfiles/blob/7c561e0a568ec717018639e128e8eea936a442a8/.config/nvim/lua/lsp.lua#L134-L137

**Comment by nyngwang** [comment]
> [...] Or these are you own setup?

Sorry, I just found your another Repo. https://github.com/lithammer/nvim-diagnosticls. So the answer is Yes.

**Comment by lithammer** [comment]
`lsp_python` is a plugin as well, however it's not public. It's just something I threw together to more intelligently find local virtualenvs.

**Comment by nyngwang** [comment]
FYI: `pylsp` is much faster than `diagnosticls` and less troublesome than `pyright`. (which I think the same reason VSCode sometimes consumes 100+% CPU usage. With pyright, a `node` process will be triggered and occupied 99% of my CPU usage)
